spring:
  redis:
    host: 111.9.116.141
    port: 6379
    database: 3
    password: iiottest
    timeout: 5s
captcha:
  timeout: 5m
  kaptcha:
    kaptcha.border: "no"
    kaptcha.background.clear.from: 238,237,230
    kaptcha.background.clear.to: 238,237,230
    kaptcha.textproducer.font.color: black
    kaptcha.noise.color: black
    kaptcha.noise.impl: com.google.code.kaptcha.impl.DefaultNoise
    kaptcha.obscurificator.impl: com.google.code.kaptcha.impl.WaterRipple
    kaptcha.image.width: 250
    kaptcha.image.height: 90
    kaptcha.textproducer.font.size: 70
    kaptcha.textproducer.char.length: 4
    kaptcha.textproducer.font.names: 宋体,楷体,微软雅黑
ladybird:
  restful-exception:
    messages:
      key_null_error:
        httpStatus: 400
        message: key不能为空
      text_null_error:
        httpStatus: 400
        message: 验证码不能为空
      text_timeout_error:
        httpStatus: 400
        message: 验证码超时
      text_error:
        httpStatus: 400
        message: 验证码不一致
      text_not_found:
        httpStatus: 400
        message: 验证码未找到